### ISSUE TITLE
Show current title on home view

### ISSUE THREAD

**Issue by mmrose** [kraiz/mopidy-schubidu#2]
Show current title with a large thumbnail on home view.

**Comment by nalch** [comment]
Implemented in kraiz/mopidy-schubidu#5

**Comment by nalch** [comment]
As of now only durations under a minute and playbackStarted events are supported.

**Comment by kraiz** [comment]
I think you mean >under one hour< as you used the time format "mm:ss" which is absolutely fine and as of my understanding the 'trackPlaybackStarted' event should always be emitted on track change which is fine too.
